language: csharp

sudo: false  # use the new container-based Travis infrastructure
dist: trusty

cache:
  yarn: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - libunwind8-dev

before_install:
  - nvm install node
  - nvm use node
  - node --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - ./build.sh